### ISSUE TITLE
Fix "method_complexity" issue in src/main/resources/public/index.js

### ISSUE THREAD

**Issue by akroon3r** [akroon3r/splunk-notification-service#76]
Function `generateWebHookUrlString` has a Cognitive Complexity of 12 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/akroon3r/splunk-notification-service/src/main/resources/public/index.js#issue_5eca08d8c0f6130001000030

**Comment by akroon3r** [comment]
If I catch you doing this before 8am on Monday, Alex is going to be **pissed**. lol

**Comment by sdevalapurkar** [comment]
working on this and will be resolved in https://github.com/akroon3r/splunk-notification-service/pull/80
