### ISSUE TITLE
Fix "method_lines" issue in src/main/resources/public/index.js

### ISSUE THREAD

**Issue by akroon3r** [akroon3r/splunk-notification-service#77]
Function `generateWebHookUrlString` has 37 lines of code (exceeds 25 allowed). Consider refactoring.

https://codeclimate.com/github/akroon3r/splunk-notification-service/src/main/resources/public/index.js#issue_5eca08d8c0f6130001000031

**Comment by akroon3r** [comment]
If I catch you doing this before 8am on Monday, Alex is going to be **pissed**. lol

**Comment by sdevalapurkar** [comment]
Working on this and will be resolved in https://github.com/akroon3r/splunk-notification-service/pull/80
